code --install-extension aaron-bond.better-comments
code --install-extension abusaidm.html-snippets
code --install-extension Angular.ng-template
code --install-extension christian-kohler.path-intellisense
code --install-extension CodeStream.codestream
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension HookyQR.beautify
code --install-extension HookyQR.minify
code --install-extension humao.rest-client
code --install-extension IBM.output-colorizer
code --install-extension johnpapa.Angular2
code --install-extension MariusAlchimavicius.json-to-ts
code --install-extension mhutchie.git-graph
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension naumovs.color-highlight
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension waderyan.gitblame
code --install-extension wmaurer.change-case
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion